### ISSUE TITLE
nlm_gaussianfield doesn't work properly

### ISSUE THREAD

**Issue by immaryw** [ropensci/NLMR#74]
Hello! I used the parameter `autocorr_range` of `nlm_gaussianfield` function to set different max range but get very similar results (especially x.3,x.4,x.5,x.6 in the plot below). Does "autocorr_range" work properly?
```r
x.1 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=5,user_seed=2021) 
x.2 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=10,user_seed=2021) 
x.3 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=20,user_seed=2021) 
x.4 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=30,user_seed=2021) 
x.5 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=40,user_seed=2021) 
x.6 <- nlm_gaussianfield(ncol=50, nrow=50, autocorr_range=50,user_seed=2021) 
varstack <- stack(x.1,x.2,x.3,x.4,x.5,x.6)
names(varstack) <- c("x.01","x.02","x.03","x.04","x.05","x.06")
show_landscape(varstack,n_col=3)

```
produce

![image](https://user-images.githubusercontent.com/17716760/115822218-05695b00-a3b9-11eb-863e-78ddf09fe49b.png)

Thanks!

**Comment by Z3tt** [comment]
Hi, thanks for using our package. The `autocorr_range` argument works as expected but you can't see any changes because your extent is too low. Here is the same code, but with landscapes consisting of 5000x5000 cells. 

![Rplot](https://user-images.githubusercontent.com/7523556/115865320-73089c00-a438-11eb-9b25-494c9f32d2f0.png)

Consider decreasing the `autocorr_range`  input, e.g. start with .1 and end with 20.

**Comment by immaryw** [comment]
Thanks for your reply!
I also tried the extent 500*500, max_lag=5,10,20,30,40,50. The last four plots still look pretty similar. Looks like when max_lag w.r.t extent grows to a certain point, the spatial structure pattern may not change anymore. In the example you gave, the ratio of max_lag/extent is very low, so the spatial structure patterns look different from each other. Can you please explain why?
